import type { Metadata } from "next";
import "./globals.css";
import { NavBar } from "./components/Navbar";
import { createClient } from "./utils/supabase/server";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = createClient().auth.getUser();
  return (
    <html lang="en">
      <body className="h-screen">
        <NavBar />
        {children}
        </body>
    </html>
  );
}
